sign_headers = "from:sender:reply-to:subject:date:message-id:to:cc:mime-version:content-type:content-transfer-encoding:content-language:resent-to:resent-cc:resent-from:resent-sender:resent-message-id:in-reply-to:references:list-id:list-help:list-owner:list-unsubscribe:list-subscribe:list-post:list-unsubscribe-post:disposition-notification-to:disposition-notification-options:original-recipient:openpgp:autocrypt";

use_esld = false;

domain {
#BT_DOMAIN_DKIM_BEGIN

#selectcircle.fr_DKIM_BEGIN
selectcircle.fr {
   selectors [
    {
      path: "/var/lib/rspamd/dkim/selectcircle.fr/default.private";
      selector: "default";
    },
    {
      path: "/var/lib/rspamd/dkim/selectcircle.fr/short.private";
      selector: "short";
    }
  ]
}
#selectcircle.fr_DKIM_END

#BT_DOMAIN_DKIM_END
}